CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(50) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'active',
    created_at BIGINT,
    updated_at BIGINT,
    permissions TEXT, -- JSON string
    last_login BIGINT,
    INDEX idx_users_status (status)
);

-- time: ISO-8601 string generated by the server. time_ms: the same instant as epoch milliseconds
-- (numeric, indexed) and used for ordering. Existing databases get time_ms and the indexes from
-- server/migrate-alerts-portfolio.cjs (CREATE TABLE IF NOT EXISTS does not alter existing tables).
CREATE TABLE IF NOT EXISTS signals (
    id VARCHAR(50) PRIMARY KEY,
    strategy VARCHAR(100),
    symbol VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL,
    price DECIMAL(20, 8) NOT NULL,
    time VARCHAR(50),
    time_ms BIGINT NULL,
    note TEXT,
    source VARCHAR(50),
    confidence FLOAT,
    INDEX idx_signals_time (time),
    INDEX idx_signals_time_ms (time_ms)
);

CREATE TABLE IF NOT EXISTS price_alerts (
    id VARCHAR(100) PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    symbol VARCHAR(50) NOT NULL,
    target_price DECIMAL(20, 8) NOT NULL,
    condition_type ENUM('ABOVE', 'BELOW') NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at BIGINT NOT NULL,
    INDEX idx_user_id (user_id),
    INDEX idx_symbol (symbol),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS portfolio_holdings (
    id VARCHAR(100) PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    symbol VARCHAR(50) NOT NULL,
    quantity DECIMAL(20, 8) NOT NULL,
    cost_basis DECIMAL(20, 8) NOT NULL,
    created_at BIGINT DEFAULT 0,
    updated_at BIGINT DEFAULT 0,
    INDEX idx_user_id (user_id),
    INDEX idx_symbol (symbol),
    UNIQUE KEY unique_user_symbol (user_id, symbol)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trade_history (
    id VARCHAR(100) PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    symbol VARCHAR(50) NOT NULL,
    side VARCHAR(10) NOT NULL,
    quantity DECIMAL(20, 8) NOT NULL,
    price DECIMAL(20, 8) NOT NULL,
    timestamp BIGINT NOT NULL,
    INDEX idx_user_id (user_id),
    INDEX idx_symbol (symbol),
    INDEX idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===== Server-side signal engine (server/index.cjs creates both tables at start with
-- CREATE TABLE IF NOT EXISTS. Without the CREATE privilege, run these two statements once by hand.)
-- No semicolons inside comments: server/migrate.cjs splits this file on them. =====

-- Shared engine state, one JSON value per key:
--   'settings'  : global engine settings (SignalSettings, version 2), edited by admins via PUT /api/engine/settings
--   'cooldowns' : per-symbol cooldown stamps of the three engines (written at most every 10 s, reloaded on start
--                 so that a restart does not re-announce a signal)
--   'boots'     : the last 50 process start times (ms), to see whether the host keeps the process alive
--   'leader'    : the engine leader's live status (heartbeat every 5 s), read by standby processes for GET /api/engine/status
--   'signals_deleted', 'signals_cleared_at' : deletions (last 200 {id, at}) and the last "delete all" (ms), relayed
--                 to the browsers of the other Node processes
CREATE TABLE IF NOT EXISTS engine_state (
    k VARCHAR(64) PRIMARY KEY,
    v LONGTEXT,
    updated_at BIGINT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Engine + measured size of engine signals (source ALGO_MOMENTUM / ALGO_VOLUME / ALGO_DIVERGENCE).
-- signal_id = signals.id, engine = 'MOMENTUM' | 'VOLUME' | 'FUNDING',
-- magnitude = JSON {"value": 5.4, "text": "5.4x", "caption": "son 1 saat hacmi / 24s ortalama saat"}.
-- GET /api/signals and the socket event 'new_signal' return both fields on the signal.
CREATE TABLE IF NOT EXISTS signal_meta (
    signal_id VARCHAR(50) PRIMARY KEY,
    engine VARCHAR(16),
    magnitude TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Forward tracking of every stored signal except the market-wide 'MARKET' aggregates (server/outcomes.cjs).
-- server/index.cjs creates it at start with CREATE TABLE IF NOT EXISTS like the two tables above.
--   market    : 'spot' or 'perp' (perp for Funding_* strategies and TradingView symbols ending in '.P', stored without '.P')
--   t0, p0    : signal time (ms) and signal price
--   o15 o60 o240 o1440 : one JSON per horizon (15 min, 1 h, 4 h, 24 h), filled by the engine leader from Binance klines:
--               {"raw", "ret", "net", "excess", "mfe", "mae", "btc", "closeAt", "resolvedAt"} or {"error", "resolvedAt"}
--               raw = close/p0 - 1, ret = direction x raw, net = ret - round-trip cost (spot 0.20 pct, perp 0.10 pct),
--               excess = direction x (raw - BTC move over the same window), NEUTRAL signals: ret / net / excess null
--   next_due  : when the next horizon (or a retry) is due, NULL when finished
--   status    : 'pending' | 'partial' | 'done' | 'skipped' (no price, symbol not on Binance, implausible price)
--   attempts  : consecutive failed fetches of the due horizons (6 -> the horizon is stored as {"error"})
CREATE TABLE IF NOT EXISTS signal_outcomes (
    signal_id VARCHAR(50) PRIMARY KEY,
    symbol VARCHAR(32) NOT NULL,
    market VARCHAR(8) NOT NULL,
    side VARCHAR(10) NOT NULL,
    strategy VARCHAR(100),
    engine VARCHAR(16) NULL,
    source VARCHAR(50) NULL,
    t0 BIGINT NOT NULL,
    p0 DOUBLE NOT NULL,
    o15 TEXT NULL,
    o60 TEXT NULL,
    o240 TEXT NULL,
    o1440 TEXT NULL,
    next_due BIGINT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'pending',
    attempts INT NOT NULL DEFAULT 0,
    note VARCHAR(255) NULL,
    INDEX idx_outcomes_next_due (next_due),
    INDEX idx_outcomes_t0 (t0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
